name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "2.11.6"

    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: sbaerlocher
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: ANSIBLE_VERSION=${{ matrix.version }}
          push: true
          tags: |
            ghcr.io/arillso/ansible:${{ matrix.version }}
            arillso/ansible:${{ matrix.version }}

  latest:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Docker image semver latest
        uses: tinact/docker.image-latest@1.0.3
        id: version
        with:
          image_name: arillso/ansible

      - name: Docker image retag docker hub
        uses: tinact/docker.image-retag@1.0.3
        with:
          image_name: arillso/ansible
          image_old_tag: ${{ steps.version.outputs.latest }}
          registry: registry.hub.docker.com
          registry_username: sbaerlocher
          registry_password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker image retag github pkg
        uses: tinact/docker.image-retag@1.0.3
        with:
          image_name: ansible
          image_old_tag: ${{ steps.version.outputs.latest }}
          registry: ghcr.io/arillso
          registry_username: sbaerlocher
          registry_password: ${{ secrets.GITHUB_TOKEN }}
