name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          #  - "4.0.0"
          - "2.10.7"
          - "2.9.22"
          - "2.8.20"

    steps:
      - uses: actions/checkout@v1

      - name: Publish docker hub
        uses: tinact/docker.image@1.0.2
        with:
          image_name: arillso/ansible
          image_tag: ${{ matrix.version }}
          dockerfile: .
          build_args: ANSIBLE_VERSION=${{ matrix.version }}
          registry: registry.hub.docker.com
          registry_username: sbaerlocher
          registry_password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish github pkg
        uses: tinact/docker.image@1.0.2
        with:
          image_name: ansible
          image_tag: ${{ matrix.version }}
          build_args: ANSIBLE_VERSION=${{ matrix.version }}
          dockerfile: .
          registry: docker.pkg.github.com/arillso/docker.ansible
          registry_username: sbaerlocher
          registry_password: ${{ secrets.GITHUB_TOKEN }}

  latest:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Docker image semver latest
        uses: tinact/docker.image-latest@1.0.3
        id: version
        with:
          image_name: arillso/ansible

      - name: Docker image retag docker hub
        uses: tinact/docker.image-retag@1.0.3
        with:
          image_name: arillso/ansible
          image_old_tag: ${{ steps.version.outputs.latest }}
          registry: registry.hub.docker.com
          registry_username: sbaerlocher
          registry_password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker image retag github pkg
        uses: tinact/docker.image-retag@1.0.3
        with:
          image_name: ansible
          image_old_tag: ${{ steps.version.outputs.latest }}
          registry: docker.pkg.github.com/arillso/docker.ansible
          registry_username: sbaerlocher
          registry_password: ${{ secrets.GITHUB_TOKEN }}
