name: Testing Container
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "2.14.1"

    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/arillso/ansible
            arillso/ansible
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=${{ matrix.version }}-test

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: ANSIBLE_VERSION=${{ matrix.version }}
          push: false
          tags: |
            ${{ steps.meta.outputs.tags }}
