name: Testing Container
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "2.12.4"

    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: sbaerlocher
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/arillso/ansible
            arillso/ansible

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: ANSIBLE_VERSION=${{ matrix.version }}
          push: false
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/arillso/ansible:${{ matrix.version }}
            arillso/ansible:${{ matrix.version }}
