name: Testing Container
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "4.0.0"
          - "2.10.7"
          - "2.9.22"
          - "2.8.20"

    steps:
      - uses: actions/checkout@master
      - name: Build Docker image
        run: docker build  --build-arg ANSIBLE_VERSION=${{ matrix.version }} --pull -t test .
      - name: Test Docker image
        run: docker run test
      - name: Inspect Docker image
        run: docker image inspect test
